### PR TITLE
Update for DF

### PR DESCRIPTION
**Pull request by Witnesscm**
Fix some errors for patch 10.0.

### CODE REVIEW

**Comment by dave-mccloskey** [comment]
Works for me

**Comment by Lilieth** [comment]
Fixed the issues. Thank you

**Comment by Uberlicious** [comment]
Can also confirm working, thanks!

**Comment by realityspeed** [comment]
What is DF guys Druid frame ?

**Comment by Maverick-PDS** [comment]
> What is DF guys Druid frame ?

Dragonflight, the new expansion.

**Comment by Maverick-PDS** [comment]
> Fix some errors for patch 10.0.

Thanks for this Witnesscm!!

Unfortunately I'm not a programmer, so I'm not sure where to download the files. Should I just be pasting the code/text via Notepad++ into the four files? Or is there a download link?

**Review by kesava-wow — APPROVED** [review]

**Comment by kesava-wow** [comment]
Thanks <3

**Pull request merged**
